
import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'pt' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  pt: {
    'nav.skills': 'Habilidades',
    'nav.experience': 'Experiência',
    'nav.projects': 'Projetos',
    'nav.certifications': 'Certificações',
    'hero.badge': '7+ Anos de Experiência em Tecnologia',
    'hero.title.1': 'Qualidade em',
    'hero.title.2': 'Cada Linha',
    'hero.title.3': 'de Código.',
    'hero.description': 'Olá, sou Bruno Salzani, Especialista em qualidade de software com 7+ anos de experiência em testes manuais e automação web. Domino ferramentas como Cypress, Selenium e Appium para garantir qualidade e agilidade em projetos complexos.',
    'hero.cta.github': 'GITHUB',
    'hero.cta.linkedin': 'LINKEDIN',
    'hero.cta.resume': 'CURRÍCULO',
    'hero.resume_url': 'https://github.com/bruno-salzani/bruno-salzani/blob/main/Curriculo.pdf',
    'hero.stats.years': 'Anos de XP',
    'hero.stats.projects': 'Projetos',
    'hero.stats.certs': 'Certificados',
    'hero.badge.expertise': 'Expertise',
    'hero.badge.focus': 'Foco',
    'hero.badge.ai': 'AI-DRIVEN DEVELOPMENT',
    'hero.badge.ai.desc': 'DOMÍNIO EM IA GENERATIVA',
    'hero.cta.projects': 'Ver Projetos',
    'hero.cta.contact': 'Contato',
    'skills.title': 'Habilidades Técnicas',
    'skills.subtitle': 'Especialidades',
    'experience.title': 'Experiência Profissional',
    'experience.subtitle': 'Trajetória',
    'projects.title': 'Meus Projetos',
    'projects.subtitle': 'Portfólio',
    'certifications.title': 'Certificações',
    'certifications.subtitle': 'Educação',
    'certifications.viewAll': 'VER TODAS AS CERTIFICAÇÕES',
    'certifications.minimize': 'MINIMIZAR CERTIFICAÇÕES',
    'certifications.quote': '"Essas certificações são um reflexo da minha jornada de aprendizado contínuo e dedicação em melhorar tanto minha expertise técnica quanto habilidades interpessoais."',
    'footer.rights': 'Todos os direitos reservados.',
    'footer.builtWith': 'Desenvolvido com React, Tailwind CSS e Framer Motion.',
    'projects.filter.all': 'VER TODOS',
    'projects.filter.qa': 'QUALIDADE / QA',
    'projects.filter.web': 'DESENVOLVIMENTO WEB',
    'projects.filter.other': 'OUTROS',
    'projects.explore': 'Explorar Código',
    'skills.languages': 'Linguagens',
    'skills.automation': 'Automação',
    'skills.tools': 'Ferramentas & Infra',
    'skills.ai': 'Domínio em IA',
    'skills.cicd': 'CI/CD & DevOps',
    'skills.management': 'Gestão & Estratégia',
    'category.qa': 'Qualidade de Software',
    'category.automation': 'Automação de Testes',
    'category.cicd': 'CI/CD',
    'category.htmlcss': 'HTML/CSS',
    'category.programming': 'Programação',
    'category.softskills': 'Habilidades Interpessoais',
    'category.others': 'Outros',
    'exp.type.fulltime': 'Tempo integral',
    'exp.location.remote': 'Remota',
    'exp.location.hybrid': 'Híbrida',
    'exp.0.role': 'Analista de teste/QA',
    'exp.0.company': 'AUREA PHIGITAL',
    'exp.0.period': 'fev de 2025 - o momento',
    'exp.0.duration': '1 ano 1 mês',
    'exp.0.desc.0': 'Arquitetura de Automação Mobile (Projeto Helios): Liderei o desenvolvimento do framework de automação mobile utilizando Appium, estruturando testes funcionais e de regressão para garantir a estabilidade das entregas em dispositivos Android e iOS.',
    'exp.0.desc.1': 'Engenharia de Testes E2E (Projeto Uranus): Desenvolvi e mantive uma robusta suíte de testes ponta a ponta utilizando Cypress com JavaScript e Cucumber (BDD). Implementei padrões de design como Page Objects (POM) para aumentar a manutenibilidade do código e reduzir o flakiness dos testes.',
    'exp.0.desc.2': 'Otimização de Cobertura e Qualidade (Artemis & Uranus): Expandi a cobertura de testes unitários nos projetos Uranus e Artemis em mais de 70%, reduzindo drasticamente a incidência de bugs em produção e acelerando o ciclo de feedback para o time de desenvolvimento.',
    'exp.0.desc.3': 'Integração Contínua (CI/CD): Responsável pela integração dos testes automatizados nas pipelines de GitLab CI e GitHub Actions. Configurei relatórios dinâmicos com Allure Reports para fornecer visibilidade em tempo real sobre a saúde dos projetos para os stakeholders.',
    'exp.0.desc.4': 'Gestão de Processos de Qualidade: Atuei no planejamento estratégico de testes, definindo métricas de qualidade e KPIs orientados a dados para impulsionar a maturidade do processo de desenvolvimento (Shift-left testing).',
    'exp.1.role': 'Analista de teste/QA',
    'exp.1.company': 'INSPAND',
    'exp.1.period': 'jun de 2018 - mai de 2024',
    'exp.1.duration': '6 anos',
    'exp.1.desc.0': 'Testes Funcionais: Desenvolvi e executei planos de testes abrangentes para aplicações Web e Mobile, aplicando metodologias como Testes Baseados em Requisitos e BDD.',
    'exp.1.desc.1': 'Testes de Integração: Realizei testes de integração com ferramentas como Postman e SoapUI, garantindo a perfeita interação entre os componentes do sistema.',
    'exp.1.desc.2': 'Automação de Testes: Criei e executei testes automatizados para aplicações Web utilizando Cypress e Selenium, com versionamento de código via Git.',
    'exp.1.desc.3': 'Testes de Desempenho: Conduzi testes de desempenho utilizando JMeter e Google Lighthouse, otimizando a estabilidade e eficiência das aplicações.',
    'exp.1.desc.4': 'Gerenciamento de Defeitos: Reportei e gerenciei defeitos utilizando Jira e Redmine, assegurando uma resolução eficiente e contribuindo para a melhoria contínua dos processos de qualidade.',
    'exp.1.desc.5': 'Analise de Requisitos: Colaborei com o Product Owner e Analista de Requisitos para refinar escopos de projeto, garantindo que todos os requisitos fossem compreendidos e corretamente implementados, identificando possíveis bugs e inconsistências.',
    'exp.1.desc.6': 'Liderança de Equipe: Recrutei e treinei novos membros da equipe de Qualidade, delegando tarefas e acompanhando o progresso das demandas para garantir entregas dentro do prazo e com alta qualidade.',
    'projects.desc.qa': 'Implementação moderna com foco em estratégias de teste automatizado, desenvolvida com abordagem AI-Driven para máxima eficiência e cobertura.',
    'projects.desc.web': 'Desenvolvimento de interfaces modernas e responsivas utilizando as melhores práticas de arquitetura e performance web.',
    'projects.desc.other': 'Projeto diversificado explorando novas tecnologias, cibersegurança e desenvolvimento especializado com suporte de IA avançada.',
    'project.2.desc': 'Plataforma mobile Enterprise de alta performance e máxima resiliência. Utiliza Java 21 e Appium sob arquitetura limpa para mitigar flakiness e garantir escalabilidade na automação de fluxos críticos de negócio.',
    'project.3.desc': 'Automação E2E resiliente para fluxos críticos de busca e reserva. Integra Selenium 4 com Resilience4j para mitigar flakiness e instabilidade. Utiliza Testcontainers para infra efêmera e técnicas avançadas de anti-bot.',
    'project.4.desc': 'Suíte E2E de nível elite com arquitetura híbrida (API + UI) e Selenium 4. Implementa Self-Healing e API Seeding para reduzir o tempo de execução em 40% e garantir resiliência total contra seletores instáveis e flakiness na UI.',
    'project.5.desc': 'Automação E2E híbrida para sistemas corporativos complexos (Selenium + API). Otimiza o setup de dados via REST, reduzindo o tempo de execução em até 70% com infraestrutura efêmera em Docker via Testcontainers e JUnit 5.',
    'project.6.desc': 'Automação de APIs híbrida (Playwright/TypeScript + RestAssured/Java). Validação rigorosa de contratos via JSON Schema com Drift Detection, fail-fast de ambiente via Zod e pipeline integrado com Allure e k6.',
    'project.7.desc': 'Automação de API de alto nível com Playwright, focada em SLAs e Resiliência. Possui injeção de caos, monitoramento de métricas (p95) via InfluxDB/CSV e Drift Detection para garantir paridade total com o contrato do Trello.',
    'project.8.desc': 'Automação de API robusta (RestAssured) com arquitetura em camadas e Clean Code. Integra testes de contrato (WireMock), performance (Gatling) e mutação (PITest) em um pipeline CI/CD avançado com Quality Gates (SonarCloud) e CodeQL.',
    'project.9.desc': 'Automação E2E para plataforma de leilões utilizando Selenium e JUnit 5. Implementa o padrão Page Objects para isolar a lógica de UI e garantir alta manutenibilidade em fluxos críticos de autenticação e cadastro de itens.',
    'project.10.desc': 'Automação E2E híbrida (UI + API) para SPA utilizando Cypress e JavaScript. Implementa comandos customizados e Page Objects com seletores estáveis, garantindo feedback rápido e relatórios detalhados via Mochawesome.',
    'project.11.desc': 'Estratégia de QA multiplataforma (Web, Mobile e API) para sistema de LMS. Validação de fluxos complexos de gamificação e integridade de dados entre camadas com Postman e SoapUI, utilizando Jira e Redmine para gestão de defeitos.',
    'project.12.desc': 'Garantia de qualidade para plataforma de gamificação multiplataforma (Web/Mobile). Validação de integridade de dados entre LMS e Frontend, com testes de API focados em performance e fidelidade dos elementos de gamificação via Postman.',
    'project.13.desc': 'Automação RPA baseada em Cypress para provisionamento em massa de dados no LMS. Realiza a conversão Excel-to-JSON para criação automatizada de cursos em lote, eliminando erros manuais e reduzindo o tempo de implantação operacional.',
    'project.14.desc': 'Estratégia de QA Mobile para aplicativo educacional nativo (iOS/Android). Validação cross-platform focada em fragmentação Android e sincronização de dados, com aplicação de Matriz de Rastreabilidade (RTM) e redução de 40% de bugs críticos.',
    'cert.0.title': 'Testes em .NET: integração e entrega contínua com Azure DevOps',
    'cert.1.title': 'Carreira QA: processos e automação de testes',
    'cert.2.title': 'Quality Assurance: plano de testes e gestão de bugs',
    'cert.3.title': 'BDD e Java: Behavior Driven Development com Cucumber',
    'cert.4.title': 'Gerenciamento de qualidade de software parte 1: o documento MDS',
    'cert.5.title': 'Fundamentos Quality Assurance: TestPlan e boas práticas',
    'cert.6.title': 'Appium: compreenda e aplique testes de interface',
    'cert.7.title': 'Selenium: testes automatizados de aceitação em Java',
    'cert.8.title': 'Cypress: automatizando testes E2E',
    'cert.9.title': 'Cypress: automação de testes E2E',
    'cert.10.title': 'Testes em .NET: testes de interface usando Selenium',
    'cert.11.title': 'Selenium WebDriver e C# parte 1: testes da sua web app',
    'cert.12.title': 'Selenium: Testes automatizados de aceitação em .NET',
    'cert.13.title': 'Integração Contínua: mais qualidade e menos risco',
    'cert.14.title': 'Testes em .NET: entrega contínua com Azure DevOps',
    'cert.15.title': 'Layouts Responsivos: layouts mobile',
    'cert.16.title': 'Web Design Responsivo',
    'cert.17.title': 'Flexbox: posicione elementos',
    'cert.18.title': 'HTML5 e CSS3 parte 4: avançando',
    'cert.19.title': 'Arquitetura CSS',
    'cert.20.title': 'Bootstrap 4: landing page responsiva',
    'cert.21.title': 'Bootstrap: single-page responsiva',
    'cert.22.title': 'HTML5 e CSS3 II: Turbinando páginas',
    'cert.23.title': 'HTML5 e CSS3 I: Primeiras páginas',
    'cert.24.title': 'HTML5 e CSS3 parte 3: formulários',
    'cert.25.title': 'HTML5 e CSS3 parte 2: posicionamento',
    'cert.26.title': 'HTML5 e CSS3 parte 1: crie uma página',
    'cert.27.title': 'ChatGPT e programação: produtividade',
    'cert.28.title': 'JavaScript e HTML: lógica de programação',
    'cert.29.title': 'Formação Vue.js',
    'cert.30.title': 'Node.js Parte 1: Inovando backend',
    'cert.31.title': 'Python: começando com a linguagem',
    'cert.32.title': 'JavaScript: programando na web',
    'cert.33.title': 'Formação C# e orientação a objetos',
    'cert.34.title': 'JavaScript: Browser e padrões de projeto',
    'cert.35.title': 'Programador de Sistemas',
    'cert.36.title': 'Programador C#',
    'cert.37.title': 'Equipes ágeis: papéis em uma equipe',
    'cert.38.title': 'Formação Líderes Comunicação e Feedback',
    'cert.39.title': 'Organização de Equipes Ágeis',
    'cert.40.title': 'Liderança: missão e propósito',
    'cert.41.title': 'Liderança: práticas de gestão',
    'cert.42.title': 'Delegação de tarefas: melhor do time',
    'cert.43.title': 'Relacionamento interpessoal',
    'cert.44.title': 'Scrum: agilidade em seu projeto',
    'cert.45.title': 'SEO: otimização de sites',
    'cert.46.title': 'Git e GitHub: colaborando em projetos',
    'cert.47.title': 'Git e Github: controle de versão',
    'cert.48.title': 'Funções com Excel: filtros e matemática',
    'cert.49.title': 'Excel procv: lógica booleana',
    'cert.50.title': 'Excel: domine o editor de planilhas',
    'cert.51.title': 'Hackaton Isat Edtechs',
    'cert.52.title': 'HTTP: Entendendo a web',
    'cert.53.title': 'Web Designer',
  },
  en: {
    'nav.skills': 'Skills',
    'nav.experience': 'Experience',
    'nav.projects': 'Projects',
    'nav.certifications': 'Certifications',
    'hero.badge': '7+ Years of Tech Experience',
    'hero.title.1': 'Quality in',
    'hero.title.2': 'Every Line',
    'hero.title.3': 'of Code.',
    'hero.description': "Hi, I'm Bruno Salzani, a Software Quality Specialist with 7+ years of experience in manual and automated web testing. I master tools like Cypress, Selenium, and Appium to ensure quality and agility in complex projects.",
    'hero.cta.github': 'GITHUB',
    'hero.cta.linkedin': 'LINKEDIN',
    'hero.cta.resume': 'RESUME',
    'hero.resume_url': 'https://github.com/bruno-salzani/bruno-salzani/blob/main/Curriculo_en.pdf',
    'hero.stats.years': 'Years of XP',
    'hero.stats.projects': 'Projects',
    'hero.stats.certs': 'Certificates',
    'hero.badge.expertise': 'Expertise',
    'hero.badge.focus': 'Focus',
    'hero.badge.ai': 'AI-DRIVEN DEVELOPMENT',
    'hero.badge.ai.desc': 'MASTERY IN GENERATIVE AI',
    'hero.cta.projects': 'View Projects',
    'hero.cta.contact': 'Contact',
    'skills.title': 'Technical Skills',
    'skills.subtitle': 'Specialties',
    'experience.title': 'Professional Experience',
    'experience.subtitle': 'Trajectory',
    'projects.title': 'My Projects',
    'projects.subtitle': 'Portfolio',
    'certifications.title': 'Certifications',
    'certifications.subtitle': 'Education',
    'certifications.viewAll': 'VIEW ALL CERTIFICATIONS',
    'certifications.minimize': 'MINIMIZE CERTIFICATIONS',
    'certifications.quote': '"These certifications are a reflection of my continuous learning journey and dedication to improving both my technical expertise and soft skills."',
    'footer.rights': 'All rights reserved.',
    'footer.builtWith': 'Built with React, Tailwind CSS, and Framer Motion.',
    'projects.filter.all': 'VIEW ALL',
    'projects.filter.qa': 'QUALITY / QA',
    'projects.filter.web': 'WEB DEVELOPMENT',
    'projects.filter.other': 'OTHERS',
    'projects.explore': 'Explore Code',
    'skills.languages': 'Languages',
    'skills.automation': 'Automation',
    'skills.tools': 'Tools & Infra',
    'skills.ai': 'AI Mastery',
    'skills.cicd': 'CI/CD & DevOps',
    'skills.management': 'Management & Strategy',
    'category.qa': 'Software Quality',
    'category.automation': 'Test Automation',
    'category.cicd': 'CI/CD',
    'category.htmlcss': 'HTML/CSS',
    'category.programming': 'Programming',
    'category.softskills': 'Soft Skills',
    'category.others': 'Others',
    'exp.type.fulltime': 'Full-time',
    'exp.location.remote': 'Remote',
    'exp.location.hybrid': 'Hybrid',
    'exp.0.role': 'Test Analyst / QA',
    'exp.0.company': 'AUREA PHIGITAL',
    'exp.0.period': 'Feb 2025 - Present',
    'exp.0.duration': '1 year 1 month',
    'exp.0.desc.0': 'Mobile Automation Architecture (Project Helios): Led the development of the mobile automation framework using Appium, structuring functional and regression tests to ensure delivery stability on Android and iOS devices.',
    'exp.0.desc.1': 'E2E Test Engineering (Project Uranus): Developed and maintained a robust end-to-end test suite using Cypress with JavaScript and Cucumber (BDD). Implemented design patterns like Page Objects (POM) to increase code maintainability and reduce test flakiness.',
    'exp.0.desc.2': 'Coverage and Quality Optimization (Artemis & Uranus): Expanded unit test coverage in Uranus and Artemis projects by over 70%, drastically reducing production bug incidence and accelerating the feedback cycle for the development team.',
    'exp.0.desc.3': 'Continuous Integration (CI/CD): Responsible for integrating automated tests into GitLab CI and GitHub Actions pipelines. Configured dynamic reports with Allure Reports to provide real-time visibility into project health for stakeholders.',
    'exp.0.desc.4': 'Quality Process Management: Acted in strategic test planning, defining quality metrics and data-driven KPIs to drive development process maturity (Shift-left testing).',
    'exp.1.role': 'Test Analyst / QA',
    'exp.1.company': 'INSPAND',
    'exp.1.period': 'Jun 2018 - May 2024',
    'exp.1.duration': '6 years',
    'exp.1.desc.0': 'Functional Testing: Developed and executed comprehensive test plans for Web and Mobile applications, applying methodologies such as Requirements-Based Testing and BDD.',
    'exp.1.desc.1': 'Integration Testing: Performed integration tests with tools like Postman and SoapUI, ensuring seamless interaction between system components.',
    'exp.1.desc.2': 'Test Automation: Created and executed automated tests for Web applications using Cypress and Selenium, with code versioning via Git.',
    'exp.1.desc.3': 'Performance Testing: Conducted performance tests using JMeter and Google Lighthouse, optimizing application stability and efficiency.',
    'exp.1.desc.4': 'Defect Management: Reported and managed defects using Jira and Redmine, ensuring efficient resolution and contributing to continuous quality process improvement.',
    'exp.1.desc.5': 'Requirements Analysis: Collaborated with the Product Owner and Requirements Analyst to refine project scopes, ensuring all requirements were understood and correctly implemented, identifying potential bugs and inconsistencies.',
    'exp.1.desc.6': 'Team Leadership: Recruited and trained new Quality team members, delegating tasks and monitoring progress to ensure on-time and high-quality deliveries.',
    'projects.desc.qa': 'Modern implementation focused on automated testing strategies, developed with an AI-Driven approach for maximum efficiency and coverage.',
    'projects.desc.web': 'Development of modern and responsive interfaces using best practices in architecture and web performance.',
    'projects.desc.other': 'Diverse project exploring new technologies, cybersecurity, and specialized development with advanced AI support.',
    'project.2.desc': 'High-performance Enterprise mobile platform with maximum resilience. Uses Java 21 and Appium under clean architecture to mitigate flakiness and ensure scalability in critical business flow automation.',
    'project.3.desc': 'Resilient E2E automation for critical search and booking flows. Integrates Selenium 4 with Resilience4j to mitigate flakiness and instability. Uses Testcontainers for ephemeral infrastructure and advanced anti-bot techniques.',
    'project.4.desc': 'Elite-level E2E suite with hybrid architecture (API + UI) and Selenium 4. Implements Self-Healing and API Seeding to reduce execution time by 40% and ensure total resilience against unstable selectors and UI flakiness.',
    'project.5.desc': 'Hybrid E2E automation for complex corporate systems (Selenium + API). Optimizes data setup via REST, reducing execution time by up to 70% with ephemeral Docker infrastructure via Testcontainers and JUnit 5.',
    'project.6.desc': 'Hybrid API automation (Playwright/TypeScript + RestAssured/Java). Rigorous contract validation via JSON Schema with Drift Detection, environment fail-fast via Zod, and integrated pipeline with Allure and k6.',
    'project.7.desc': 'High-level API automation with Playwright, focused on SLAs and Resilience. Features chaos injection, metric monitoring (p95) via InfluxDB/CSV, and Drift Detection to ensure total parity with the Trello contract.',
    'project.8.desc': 'Robust API automation (RestAssured) with layered architecture and Clean Code. Integrates contract testing (WireMock), performance (Gatling), and mutation testing (PITest) in an advanced CI/CD pipeline with Quality Gates (SonarCloud) and CodeQL.',
    'project.9.desc': 'E2E automation for auction platform using Selenium and JUnit 5. Implements Page Objects pattern to isolate UI logic and ensure high maintainability in critical authentication and item registration flows.',
    'project.10.desc': 'Hybrid E2E automation (UI + API) for SPA using Cypress and JavaScript. Implements custom commands and Page Objects with stable selectors, ensuring fast feedback and detailed reports via Mochawesome.',
    'project.11.desc': 'Multi-platform QA strategy (Web, Mobile, and API) for LMS system. Validation of complex gamification flows and data integrity across layers with Postman and SoapUI, using Jira and Redmine for defect management.',
    'project.12.desc': 'Quality assurance for multi-platform gamification platform (Web/Mobile). Validation of data integrity between LMS and Frontend, with API tests focused on performance and fidelity of gamification elements via Postman.',
    'project.13.desc': 'Cypress-based RPA automation for mass data provisioning in LMS. Performs Excel-to-JSON conversion for automated batch course creation, eliminating manual errors and reducing operational deployment time.',
    'project.14.desc': 'Mobile QA strategy for native educational app (iOS/Android). Cross-platform validation focused on Android fragmentation and data synchronization, with application of Traceability Matrix (RTM) and 40% reduction in critical bugs.',
    'cert.0.title': '.NET Testing: Continuous Integration and Delivery with Azure DevOps',
    'cert.1.title': 'QA Career: Processes and Test Automation',
    'cert.2.title': 'Quality Assurance: Test Plan and Bug Management',
    'cert.3.title': 'BDD and Java: Behavior Driven Development with Cucumber',
    'cert.4.title': 'Software Quality Management Part 1: The MDS Document',
    'cert.5.title': 'Quality Assurance Foundations: TestPlan and Best Practices',
    'cert.6.title': 'Appium: Understand and Apply Interface Testing',
    'cert.7.title': 'Selenium: Automated Acceptance Testing in Java',
    'cert.8.title': 'Cypress: Automating E2E Tests',
    'cert.9.title': 'Cypress: E2E Test Automation',
    'cert.10.title': '.NET Testing: Interface Testing using Selenium',
    'cert.11.title': 'Selenium WebDriver and C# Part 1: Testing your Web App',
    'cert.12.title': 'Selenium: Automated Acceptance Testing in .NET',
    'cert.13.title': 'Continuous Integration: More Quality and Less Risk',
    'cert.14.title': '.NET Testing: Continuous Delivery with Azure DevOps',
    'cert.15.title': 'Responsive Layouts: Mobile Layouts',
    'cert.16.title': 'Responsive Web Design',
    'cert.17.title': 'Flexbox: Position Elements',
    'cert.18.title': 'HTML5 and CSS3 Part 4: Advancing',
    'cert.19.title': 'CSS Architecture',
    'cert.20.title': 'Bootstrap 4: Responsive Landing Page',
    'cert.21.title': 'Bootstrap: Responsive Single-Page',
    'cert.22.title': 'HTML5 and CSS3 II: Boosting Pages',
    'cert.23.title': 'HTML5 and CSS3 I: First Pages',
    'cert.24.title': 'HTML5 and CSS3 Part 3: Forms',
    'cert.25.title': 'HTML5 and CSS3 Part 2: Positioning',
    'cert.26.title': 'HTML5 and CSS3 Part 1: Create a Page',
    'cert.27.title': 'ChatGPT and Programming: Productivity',
    'cert.28.title': 'JavaScript and HTML: Programming Logic',
    'cert.29.title': 'Vue.js Training',
    'cert.30.title': 'Node.js Part 1: Innovating Backend',
    'cert.31.title': 'Python: Starting with the Language',
    'cert.32.title': 'JavaScript: Programming on the Web',
    'cert.33.title': 'C# and Object-Oriented Training',
    'cert.34.title': 'JavaScript: Browser and Design Patterns',
    'cert.35.title': 'Systems Programmer',
    'cert.36.title': 'C# Programmer',
    'cert.37.title': 'Agile Teams: Roles in a Team',
    'cert.38.title': 'Leadership Training: Communication and Feedback',
    'cert.39.title': 'Agile Team Organization',
    'cert.40.title': 'Leadership: Mission and Purpose',
    'cert.41.title': 'Leadership: Management Practices',
    'cert.42.title': 'Task Delegation: Best of the Team',
    'cert.43.title': 'Interpersonal Relationship',
    'cert.44.title': 'Scrum: Agility in your Project',
    'cert.45.title': 'SEO: Website Optimization',
    'cert.46.title': 'Git and GitHub: Collaborating on Projects',
    'cert.47.title': 'Git and GitHub: Version Control',
    'cert.48.title': 'Excel Functions: Filters and Math',
    'cert.49.title': 'Excel PROCV: Boolean Logic',
    'cert.50.title': 'Excel: Master the Spreadsheet Editor',
    'cert.51.title': 'Isat Edtechs Hackathon',
    'cert.52.title': 'HTTP: Understanding the Web',
    'cert.53.title': 'Web Designer',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'pt';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
